### ISSUE TITLE
execpod default command bash

### ISSUE THREAD

**Issue by Aracki** [thecasualcoder/kube-fzf#10]
Is it possible to make `execpod`'s default command to be `bash`.

I know there will be no bash in some containers, buy maybe if that fails we can do `sh`.

**Comment by arunvelsriram** [comment]
I would prefer `sh` as we can blindly assume that all containers will have `sh`.

Am not sure how to find out if a container has `bash`. If you could think of a way to check if a container has `bash` upfront please raise a PR.

**Comment by arunvelsriram** [comment]
Closing this for now. Feel free to share your thoughts.

**Comment by Aracki** [comment]
Didn't find a way, without actually exec-ing into the container. 

The only way I can think of is to try to exec with `bash` and if there is an error, fire up another command with `sh`.
