### ISSUE TITLE
[Feature Request] pfpod should open in browser after port-forwarding

### ISSUE THREAD

**Issue by dineshba** [thecasualcoder/kube-fzf#11]
After successful port forward with given `$PORT`  using `pfpod`, Can we open localhost:$PORT in the browser.

May be with a flag 
```bash
 pfpod -n namespace --open $PORT
```

**Comment by arunvelsriram** [comment]
Fixed by @dineshba in #14

**Comment by jskswamy** [comment]
@dineshba @arunvelsriram can the port information can be copied to clipboard by default?

**Comment by dineshba** [comment]
@jskswamy @arunvelsriram Can we make as default ? Or can we add another flag ?

**Comment by jskswamy** [comment]
@dineshba I prefer it to be a default option rather than additional flag, most of the time next immediate action would be to use the port forwarded info for doing `cURL` or something similar

**Comment by arunvelsriram** [comment]
I think both are fine.

One more point I wanted to discuss is that we have to make sure open and copy to clipboard works on Mac as well as Linux.

**Comment by jskswamy** [comment]
@arunvelsriram we could use`xclip` for Linux and `pbcopy` for Mac but one catch is `xclip` is not available in all distro by default.
