### ISSUE TITLE
kube-fzf.sh collides with kube-fzf.sh in PATH on devlopment machines

### ISSUE THREAD

**Issue by arunvelsriram** [thecasualcoder/kube-fzf#15]
@dineshba pointed out that:

All kube-fzf commands expects `kube-fzf.sh` to be in the path. For eg:
[https://github.com/thecasualcoder/kube-fzf/blob/9cef0b6e980c8cba7760419a5202db3034745aa8/describepod#L3](https://github.com/thecasualcoder/kube-fzf/blob/9cef0b6e980c8cba7760419a5202db3034745aa8/describepod#L3)

This doesn't work for development as we will be modifying local `kube-fzf.sh` but the commands will keep using the global `kube-fzf.sh` from `PATH`. So to ease development, we will have to `source` the local `kube-fzf.sh` during development.

**Comment by dineshba** [comment]
Fixed by @viveksoundrapandi
