### ISSUE TITLE
need to add --kubeconfig flag

### ISSUE THREAD

**Issue by developer-guy** [thecasualcoder/kube-fzf#24]
i think we should add --kubeconfig flag to fetch configs from given path. @bonnefoa

**Comment by arunvelsriram** [comment]
All the commands internally use `kubectl` so you could make use of `KUBECONFIG` environment variable to specify additional configs.

https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#the-kubeconfig-environment-variable
